version: '3.3'
services:
  tyk-mdcb: 
    image: tykio/tyk-mdcb-docker:v1.7.5
    volumes: 
    - ./confs/sink.conf:/opt/tyk-sink/tyk_sink.conf
    ports:
    - "9090:9090"
    depends_on:
    - tyk-redis
    - tyk-mongo
    - tyk-mgateway
    - tyk-dashboard
    networks:
    - tyk
    environment:
    - TYK_MDCB_LICENSE=${MDCB_LICENCE:?Please set MDCB_LICENCE in .env}
  tyk-dashboard:
    image: tykio/tyk-dashboard:v3.2.2
    ports:
    - "3000:3000"
    - "5000:5000"
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    volumes: 
    - ./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
    - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE:?Dashboard licence missing from Docker environment file .env. Review The Getting Started steps in README.md.}
  tyk-mgateway:
    image: tykio/tyk-gateway:v3.2.2
    volumes:
      - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./middleware:/opt/tyk-gateway/middleware
    ports:
    - "8081:8081"
    networks:
    - tyk
    depends_on:
    - tyk-redis
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    volumes:
      - ./confs/pump.conf:/opt/tyk-pump/pump.conf  
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    - tyk-mgateway
  tyk-redis:
    image: redis
    ports:
    - "6380:6379"
    volumes:
    - redis-data:/data
    networks:
    - tyk
  tyk-mongo:
    image: mongo:4.0.2
    command: ["mongod", "--smallfiles"]
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
    networks:
    - tyk

volumes:
  redis-data:
  mongo-data:

networks:
  tyk:
